// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package reason_im

import (
	"reason-im/internal/config/mysql"
	"reason-im/internal/repo"
	"reason-im/internal/service"
	mysql2 "reason-im/internal/utils/mysql"
)

// Injectors from wire.go:

func InitUserService() service.UserService {
	databaseTpl := _wireDatabaseTplValue
	userDao := repo.NewUserDao(databaseTpl)
	friendDao := repo.NewFriendDao(databaseTpl)
	userService := service.NewUserService(userDao, friendDao)
	return userService
}

var (
	_wireDatabaseTplValue = tpl
)

func InitInviteFriendService() service.FriendInviteService {
	databaseTpl := _wireMysqlDatabaseTplValue
	friendInviteDao := repo.NewFriendInviteDao(databaseTpl)
	friendDao := repo.NewFriendDao(databaseTpl)
	userDao := repo.NewUserDao(databaseTpl)
	friendInviteService := service.NewFriendInviteService(friendInviteDao, friendDao, userDao, databaseTpl)
	return friendInviteService
}

var (
	_wireMysqlDatabaseTplValue = tpl
)

func InitFriendService() service.FriendService {
	databaseTpl := _wireDatabaseTplValue2
	friendDao := repo.NewFriendDao(databaseTpl)
	friendService := service.NewFriendService(friendDao)
	return friendService
}

var (
	_wireDatabaseTplValue2 = tpl
)

func InitGroupService() service.GroupService {
	databaseTpl := _wireDatabaseTplValue3
	groupDao := repo.NewGroupDao(databaseTpl)
	userDao := repo.NewUserDao(databaseTpl)
	groupMemberDao := repo.NewGroupMemberDao(databaseTpl)
	groupMemberInviteDao := repo.NewGroupMemberInviteDao(databaseTpl)
	groupService := service.NewGroupService(groupDao, userDao, groupMemberDao, groupMemberInviteDao, databaseTpl)
	return groupService
}

var (
	_wireDatabaseTplValue3 = tpl
)

func InitMsgService() service.MsgService {
	databaseTpl := _wireDatabaseTplValue4
	friendDao := repo.NewFriendDao(databaseTpl)
	msgService := service.NewMsgService(friendDao)
	return msgService
}

var (
	_wireDatabaseTplValue4 = tpl
)

// wire.go:

var datasource = mysql.Datasource()

var tpl = mysql2.NewDatabaseTpl(datasource)
